version: '3.8'

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    volumes:
      - mysql_vol:/var/lib/mysql
    container_name: mariadb
    networks:
      - mynet
    expose:
      - "3306"
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/
    image: wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    env_file:
      - .env
    networks:
      - mynet
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    restart: always
    expose:
      - "9000"
    

  nginx:
    build: requirements/nginx/
    image: nginx
    depends_on:
      - wordpress
    container_name: nginx
    env_file:
      - .env
    networks:
      - mynet
    volumes:
      - wordpress_vol:/var/www/html/wordpress
      - adminer_vol:/var/www/html/adminer
      - portfolio_vol:/var/www/html/portfolio
      - nginx_vol:/etc/nginx/conf.d
    ports:
      - "443:443"
    restart: always

  adminer:
    build: requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    networks:
      - mynet
    expose: 
      - "8080"
    restart: always
    depends_on:
      - mariadb
    volumes:
      - adminer_vol:/var/www/html/adminer

  ftp-server:
    build: requirements/bonus/ftp-server
    image: ftp-server
    container_name: ftp-server
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - mynet
    ports:
      - "20:20"
      - "21:21"
    restart: always
    depends_on:
      - wordpress

  portfolio:
    build: requirements/bonus/portfolio
    image: portfolio
    container_name: portfolio
    volumes:
      - portfolio_vol:/var/www/html/portfolio
      - nginx_vol:/etc/nginx/conf.d

  redis:
    build: requirements/bonus/redis
    image: redis
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - mynet

  cadvisor:
    build: requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynet
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg
    privileged: true

volumes:
  mysql_vol:
    driver: local
    driver_opts:
      type: none
      device:
        ${HOME}/data/mysql_db
      o: "bind"

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device:
        ${HOME}/data/wordpress_path
      o: "bind"

  adminer_vol:
    driver: local
    driver_opts:
      type: none
      device:
        ${HOME}/data/adminer_path
      o: bind

  portfolio_vol:
    driver: local
    driver_opts:
      type: none
      device:
        ${HOME}/data/portfolio_path
      o: bind

  nginx_vol:
networks:
  mynet: