version: "3.8"

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadbc
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - mynet
    volumes:
      - mysql_vol:/var/lib/mysql

  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    container_name: wordpressc
    env_file:
      - .env
    networks:
      - mynet
    volumes:
      - wordpress_vol:/var/www/html/wordpress

  nginx:
    build: requirements/nginx/
    depends_on:
      - wordpress
    container_name: nginxc
    env_file:
      - .env
    networks:
      - mynet
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    ports:
      - "443:443"
      


volumes:
  mysql_vol:
    driver: local
    driver_opts:
      type: none
      device:
        ${HOME}/data/mysql_db
      o: "bind"

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device:
        ${HOME}/data/wordpress_path
      o: "bind"


networks:
  mynet: